#!/usr/bin/env bash
# Vendors all third-party front-end assets locally so the site is fully
# self-contained (no runtime CDN calls). Re-run this to refresh the pinned
# versions. Tailwind (assets/js/tailwind.js) is already vendored separately.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FONTS_DIR="$SCRIPT_DIR/assets/fonts"
CSS_DIR="$SCRIPT_DIR/assets/css"
JS_DIR="$SCRIPT_DIR/assets/js"

UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36"

# Pinned versions
GOOGLE_FONTS_URL="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&family=Playfair+Display:wght@700&display=swap"
MARKED_URL="https://cdn.jsdelivr.net/npm/marked@12.0.2/marked.min.js"
DOMPURIFY_URL="https://cdn.jsdelivr.net/npm/dompurify@3.1.6/dist/purify.min.js"
# Lucide (icons), tracking latest. v1+ dropped the brand/social logos
# (Facebook, Instagram, LinkedIn); those three are supplied locally by the
# hand-authored assets/js/brand-icons.js (not fetched here).
LUCIDE_URL="https://cdn.jsdelivr.net/npm/lucide@1.22.0/dist/umd/lucide.min.js"

# Only these subsets are kept (English + Western/European). Drop the rest.
KEEP_SUBSETS="latin latin-ext"

mkdir -p "$FONTS_DIR" "$CSS_DIR" "$JS_DIR"

echo "==> Fonts: fetching Google Fonts CSS"
RAW_CSS="$(curl -fsSL -A "$UA" "$GOOGLE_FONTS_URL")"

echo "==> Fonts: downloading woff2 files and building assets/css/fonts.css"
KEEP_SUBSETS="$KEEP_SUBSETS" FONTS_DIR="$FONTS_DIR" CSS_DIR="$CSS_DIR" UA="$UA" \
python3 - "$RAW_CSS" <<'PY'
import os, re, sys, urllib.request

raw = sys.argv[1]
fonts_dir = os.environ["FONTS_DIR"]
css_dir = os.environ["CSS_DIR"]
keep = set(os.environ["KEEP_SUBSETS"].split())
ua = os.environ["UA"]

# Each face is preceded by a "/* subset */" comment in Google's output.
pattern = re.compile(r"/\*\s*(?P<subset>[a-z0-9-]+)\s*\*/\s*(?P<face>@font-face\s*\{.*?\})", re.DOTALL)

def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")

out_blocks = []
downloaded = 0
for m in pattern.finditer(raw):
    subset = m.group("subset")
    face = m.group("face")
    if subset not in keep:
        continue
    fam = re.search(r"font-family:\s*'([^']+)'", face).group(1)
    weight = re.search(r"font-weight:\s*(\d+)", face).group(1)
    style = re.search(r"font-style:\s*(\w+)", face).group(1)
    url = re.search(r"url\(([^)]+)\)", face).group(1).strip("'\"")
    fname = f"{slug(fam)}-{weight}-{style}-{subset}.woff2"
    dest = os.path.join(fonts_dir, fname)
    req = urllib.request.Request(url, headers={"User-Agent": ua})
    with urllib.request.urlopen(req) as r, open(dest, "wb") as f:
        f.write(r.read())
    downloaded += 1
    local_face = face.replace(url, f"/assets/fonts/{fname}")
    out_blocks.append(f"/* {fam} {weight} {style} ({subset}) */\n{local_face}")

header = ("/* Self-hosted fonts. Generated by fetch-assets.sh from Google Fonts.\n"
         "   Do not edit by hand; re-run the script to regenerate. */\n\n")
with open(os.path.join(css_dir, "fonts.css"), "w") as f:
    f.write(header + "\n\n".join(out_blocks) + "\n")

print(f"    {downloaded} woff2 files -> {fonts_dir}")
PY

echo "==> JS: marked.min.js"
curl -fsSL -A "$UA" "$MARKED_URL" -o "$JS_DIR/marked.min.js"
echo "==> JS: purify.min.js (DOMPurify)"
curl -fsSL -A "$UA" "$DOMPURIFY_URL" -o "$JS_DIR/purify.min.js"
echo "==> JS: lucide.min.js (icons)"
curl -fsSL -A "$UA" "$LUCIDE_URL" -o "$JS_DIR/lucide.min.js"

echo "==> Done. Vendored assets:"
ls -1 "$FONTS_DIR"
echo "    assets/css/fonts.css"
echo "    assets/js/marked.min.js"
echo "    assets/js/purify.min.js"
echo "    assets/js/lucide.min.js"
